name:                polysemy
version:             1.9.1.1
github:              "polysemy-research/polysemy"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "https://funprog.zulipchat.com/#narrow/stream/216942-Polysemy"
copyright:           "2019-2023 The Polysemy Lounge"
build-type:          Custom

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Higher-order, low-boilerplate free monads.
category:            Language

description:         Please see the README on GitHub at <https://github.com/polysemy-research/polysemy#readme>

dependencies:
- base >= 4.9 && < 5
- containers >= 0.5 && < 0.7
- mtl >= 2.2.2 && < 3
- syb >= 0.7 && < 0.8
- stm >= 2 && < 3
- template-haskell >= 2.12.0.0 && < 3
- th-abstraction >= 0.3.1.0 && < 0.7
- transformers >= 0.5.2.0 && < 0.7
- first-class-families >= 0.5.0.0 && < 0.9
- unagi-chan >= 0.4.0.0 && < 0.5
- async >= 2.2 && < 3
- type-errors >= 0.2.0.0

custom-setup:
  dependencies:
    - base >= 4.9 && < 5
    - Cabal <3.11
    - cabal-doctest >=1.0.6 && <1.1

default-extensions:
  - BlockArguments
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - UnicodeSyntax

when:
  - condition: impl(ghc < 8.6)
    default-extensions:
      - MonadFailDesugaring
      - TypeInType

library:
  ghc-options: -Wall
  source-dirs: src
  other-modules: Polysemy.Internal.PluginLookup
  generated-other-modules:
  - Paths_polysemy

  when:
    - condition: impl(ghc < 8.2.2)
      dependencies:
        - unsupported-ghc-version > 1 && < 1

tests:
  polysemy-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy
    - inspection-testing >= 0.4.2 && < 0.6
    - hspec >= 2.6.0 && < 3
    - doctest >= 0.16.0.1 && < 0.23
    - hspec-discover >= 2.0
    generated-other-modules:
    - Build_doctests

