name:                too-fast-too-free
version:             0.1.0.0
github:              "isovector/too-fast-too-free"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/too-fast-too-free#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- mtl

library:
  ghc-options: -O2
  source-dirs: src

executables:
  too-fast-too-free-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - too-fast-too-free

tests:
  too-fast-too-free-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - too-fast-too-free

benchmarks:
  too-fast-too-free-bench:
    source-dirs: bench
    main: countDown.hs
    dependencies:
    - criterion
    - free
    - freer-simple
    - mtl
    - too-fast-too-free
