resolver: lts-13.0

packages:
- .
- polysemy-plugin

extra-deps:
- aeson-1.4.3.0
- bifunctors-5.5.4
- dump-core-0.1.3.2
- first-class-families-0.6.0.0
- ghc-lib-0.20190204
- inspection-testing-0.4.2
- loopbreaker-0.1.1.1
- monadLib-3.9
- th-abstraction-0.3.1.0
- unagi-chan-0.4.1.3
- type-errors-0.2.0.0
- type-errors-pretty-0.0.1.0
