name:                polysemy-plugin
version:             0.2.0.2
github:              "isovector/polysemy"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Disambiguate obvious uses of effects.
category:            Polysemy

description:         Please see the README on GitHub at <https://github.com/isovector/polysemy/tree/master/polysemy-plugin#readme>

dependencies:
- base >= 4.7 && < 5
- ghc >= 8.6.3 && < 8.7
- ghc-tcplugins-extra >= 0.3 && < 0.4
- polysemy >= 0.1
- syb >= 0.7 && <0.8
- transformers >= 0.5.5.0 && < 0.6
- containers >= 0.6 && <= 0.7

library:
  source-dirs: src

tests:
  polysemy-plugin-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    - -O2
    dependencies:
    - polysemy >= 0.3
    - polysemy-plugin
    - hspec >= 2.6.0 && < 3
    - should-not-typecheck >= 2.1.0 && < 3
    - inspection-testing >= 0.4.2 && < 0.5

default-extensions:
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeFamilies

  - UnicodeSyntax
