module Main where
import Test.DocTest
main :: IO ()
main = doctest
    [ "-isrc"
    , "/home/sandy/prj/polysemy/src/Polysemy.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Error.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Fixpoint.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/IO.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Input.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/Combinators.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/CustomErrors.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/Effect.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/Fixpoint.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/Lift.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/NonDet.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/PluginLookup.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/TH/Effect.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/Tactics.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Internal/Union.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/NonDet.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Output.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Reader.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Resource.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/State.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Trace.hs"
    , "/home/sandy/prj/polysemy/src/Polysemy/Writer.hs"
    , "-XDataKinds"
    , "-XDeriveFunctor"
    , "-XFlexibleContexts"
    , "-XGADTs"
    , "-XLambdaCase"
    , "-XPolyKinds"
    , "-XRankNTypes"
    , "-XScopedTypeVariables"
    , "-XStandaloneDeriving"
    , "-XTypeApplications"
    , "-XTypeOperators"
    , "-XTypeFamilies"
    , "-XUnicodeSyntax"
    , "-XTemplateHaskell"
    ]

